### ISSUE TITLE
Unbenötigte Dateien entfernen

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/Ini-S-Scanner#6]
Die `.markdownlint.json` ist einerseits nicht valide, andererseits stellt sich die Frage, ob die Datei überhaupt benötigt wird.

Bitte prüfen.

**Comment by Skeeve** [comment]
Valide habe ich sie gemacht (ein Komma zuviel).

Verwendet wird sie nur wenn man die `texts.XX.md` Dateien mit markdownlint validieren möchte.

Markdownlint möchte beispielsweise keine identischen Überschriften (MD024). Das brauchen wir aber zwingend.

Mit MD013 wird bestimmt, daß Zeilenlängen nicht begrenzt sein sollen.

MD033 wiederum erlaubt Inline-HTML.
